"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7h%_(hicwl59ff8&chf^%8)nh45(s31xuy@&2ke5btc-cu470b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'bookshelf',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'relationship_app',
    
]

MIDDLEWARE = [
    # LibraryProject/settings.py (CSP Configuration)

# --- Content Security Policy (CSP) ---
# NOTE ON DOCUMENTATION: CSP mitigates XSS by telling the browser which sources 
# of content (scripts, styles, images) are trusted.
    'csp.middleware.CspMiddleware', # Add the CSP middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'bookshelf.CustomUser'

# LibraryProject/LibraryProject/settings.py (Security Configuration)

# --- General Production/Security Settings ---
# MUST be set to False in a production environment
DEBUG = False
# Replace with your domain when DEBUG is False
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'your-domain.com'] 

# --- Security Headers and Protections ---

# 1. Clickjacking Protection
# Prevents the site from being loaded in a frame/iframe on another site.
X_FRAME_OPTIONS = 'DENY' 

# 2. XSS and MIME Sniffing Protection
# Prevents browsers from attempting to guess the content type (MIME sniffing),
# which can mitigate certain XSS attacks.
SECURE_CONTENT_TYPE_NOSNIFF = True

# 3. Secure Cookie Enforcement (Requires HTTPS)
# Ensures the CSRF cookie is only sent over a secure connection (HTTPS).
CSRF_COOKIE_SECURE = True
# Ensures the session cookie is only sent over a secure connection (HTTPS).
SESSION_COOKIE_SECURE = True

# 4. Deprecated but often checked setting (for compatibility/completeness)
# Django now handles this via the Content-Type header and middleware, but 
# we include it for the specific check requirement.
SECURE_BROWSER_XSS_FILTER = True

# Define the CSP settings here:
CSP_DEFAULT_SRC = ("'self'",) # Only allow content from your own domain
CSP_SCRIPT_SRC = ("'self'", 'https://trustedscripts.com',) # Only allow scripts from self and a specific trusted domain
CSP_STYLE_SRC = ("'self'", 'https://trustedstyles.com', "'unsafe-inline'",) # Allow self and inline styles (often needed)
CSP_IMG_SRC = ("'self'", "data:") # Allow images from self and data URIs
CSP_FRAME_ANCESTORS = ("'self'",) # Prevents embedding the site in frames by unauthorized origins